//! Copies ./hooks/<agent>/* into $OUT_DIR/assets and generates assets.rs,
//! which embeds each file as a (name, contents) pair. `jam setup` installs
//! from these embedded payloads so the binary stays self-contained.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const AGENTS: &[&str] = &["claude-code", "codex", "opencode", "pi"];

fn main() {
    println!("cargo:rerun-if-changed=hooks");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let assets_dir = out_dir.join("assets");

    let mut code = String::from(
        "// Generated by build.rs from ./hooks. One (file name, contents) slice per agent.\n",
    );
    for agent in AGENTS {
        let dst_dir = assets_dir.join(agent);
        fs::create_dir_all(&dst_dir).expect("create asset dir");
        let mut entries = Vec::new();
        for (name, src) in hook_files(&Path::new("hooks").join(agent)) {
            let dst = dst_dir.join(&name);
            fs::copy(&src, &dst).expect("copy hook file to OUT_DIR");
            entries.push(format!(
                "(\"{name}\", include_str!(r\"{}\"))",
                dst.display()
            ));
        }
        let ident = agent.to_uppercase().replace('-', "_");
        code.push_str(&format!(
            "pub static {ident}: &[(&str, &str)] = &[{}];\n",
            entries.join(", ")
        ));
    }
    fs::write(out_dir.join("assets.rs"), code).expect("write assets.rs");
}

/// Regular files in the agent's hooks dir, sorted for a stable embed order.
/// Dotfiles (.gitkeep) are placeholders, not payloads.
fn hook_files(dir: &Path) -> Vec<(String, PathBuf)> {
    let Ok(entries) = fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut files: Vec<(String, PathBuf)> = entries
        .filter_map(Result::ok)
        .filter(|e| e.path().is_file())
        .filter_map(|e| e.file_name().into_string().ok().map(|n| (n, e.path())))
        .filter(|(name, _)| !name.starts_with('.'))
        .collect();
    files.sort();
    files
}
